### ISSUE TITLE
Wiki creation

### ISSUE THREAD

**Issue by Koliopkl** [plexil-rwl-support/semantic-tests#3]
Neither I nor @ajjimenezm can create wiki pages because we don't have the permissions. @mfeliu if you can, could you grant us the needed permissions?

**Comment by mfeliu** [comment]
Probad ahora.

**Comment by Koliopkl** [comment]
Hola @mfeliu, Santiago nos pasó su usuario de GitHub para que le añadieras a este repositorio. Es sescobarUPV. Podrías añadirlo, ¿por favor?

**Comment by mfeliu** [comment]
Por cierto, podeis editar anyadir paginas a la wiki? Si es afirmativo, cerrad esta issue ;-)
